config:
  target: "https://try-syndicate.org"
  phases:
    - duration: 30    # Run the test for 5 minutes
      arrivalRate: 10  # Start with 10 users per second
    # - duration: 300
    #   arrivalRate: 50  # Increase to 50 users per second
    # - duration: 300
    #   arrivalRate: 100 # Stress with 100 users per second
  tls:
    rejectUnauthorized: false # For self-signed certificates, disable strict validation
  # payload:
  #   # Optionally, load test data (e.g., session tokens or user data) from a CSV file
  #   path: "test_data.csv"
  #   fields:
  #     - session_id
  #     - username

scenarios:
  - flow:
      - log: "Connecting to the LiveView endpoint"
      - websocket:
          # Connect to the Phoenix LiveView socket
          request:
            url: "/live/websocket"
            query: "vsn=2.0.0"
          open:
            # Step 1: Join the LiveView endpoint
            text: '{"topic":"lv:phx","event":"phx_join","payload":{},"ref":"1"}'
            match:
              - type: response
                expect: '{"event":"phx_reply","status":"ok"}'
          actions:
            # Step 2: Simulate a user action that triggers a LiveView event
            # - send:
            #     text: '{"topic":"lv:phx","event":"event_name","payload":{"data":"value"},"ref":"2"}'
            # # Step 3: Wait for a response (optional)
            # - receive:
            #     match: '{"event":"phx_reply"}'
            # # Step 4: Simulate idle time
            # - think: 5
            # # Step 5: Repeat another user action
            # - send:
            #     text: '{"topic":"lv:phx","event":"another_event","payload":{"action":"test"},"ref":"3"}'
            - think: 2
          close: true
