config:
  target: "https://try-syndicate.org" # Base URL of your application
  phases:
    - duration: 20 # Run the test for 60 seconds
      arrivalRate: 1 # Simulate 5 users arriving per second

scenarios:
  - flow:
      - log: "Fetching the LiveView page to extract the CSRF token"
      - http:
          url: "/"
          method: GET
          capture:
            - selector: "meta[name='csrf-token']"
              attribute: "content"
              as: "csrfToken"
      - log: "Connecting to LiveView WebSocket"
      - websocket:
          request:
            url: "/live/websocket"
            query: "vsn=2.0.0&_csrf_token={{ csrfToken }}"
          actions:
            - send:
                text: '{"topic":"lv:phx","event":"phx_join","payload":{},"ref":"1"}'
            - receive:
                match: '{"event":"phx_reply"}'
            - log: "Message successfully sent and reply received"
